language: node_js
node_js:
- node
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_fbdbd197bbf4_key -iv $encrypted_fbdbd197bbf4_iv
  -in service-account.json.enc -out service-account.json -d
deploy:
  provider: gae
  keyfile: service-account.json
  project: puppeteerexamples
addons:
  ssh_known_hosts:
  - github.com
  - 192.30.253.112
  - 192.30.253.113
branches:
  only:
  - master
